name: Deploy docker images to GitHub registry

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  buildQueuePythonImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image and push it to GitHub
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/queue_python
          tag_with_ref: true
          path: queue_python/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
